version: '3.8'

services:
  app:
    image: app-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/u01/app/oracle
    networks:
      - app-network

networks:
  app-network:

volumes:
  oracle-data: